### ISSUE TITLE
File IO

### ISSUE THREAD

**Issue by snystrom** [How-to-Learn-to-Code/rclass#10]
Vignette is [here](https://github.com/How-to-Learn-to-code/rclass/blob/file_io/vignettes/file_io_cleaning.Rmd)

I haven't been keeping totally up on how you're managing the package environment but currently I've got a download.file command in there which I'm assuming I can drop out in favor of dropping the data into `data/`?

I've used lots of `dplyr` code and the `readr` family of import functions, so hope that's not an issue. I think it really shines for data cleaning since you wind up doing so many repetitive tasks.

Take a look and tell me what you think. I'll switch over to the correct contributing style for the pull request.

**Comment by daynefiler** [comment]
I've also been working on an input/output lesson this morning. I think we should merge them. I can handle getting it into the formatting and package. The `download.file` function is totally fine. I have  a brief section about connections, so that would be a nice transition. We will need other instructors to chime in, but I am strongly against using `dplyr` functions.  I just think the class should focus on the native R approach. If they get that down they can move onto things like the tidyverse and data.table. 

What are you using magrittr for?

**Comment by daynefiler** [comment]
If you want to reduce the repetitive code, one option would be to move the control lecture up before IO, and then use for-loops to do the repetitive work.

**Comment by daynefiler** [comment]
I am going to open a PR for your branch and #6. My lesson is incomplete, but we can open a new issue to merge them into one which will also handle any formatting and package issues.

**Comment by snystrom** [comment]
That's kind of a holdover from my usual workflow which is to import `magrittr` for the pipes and call dplyr functions with `dplyr::fun()` since the generic names overlap so many other package functions I use regularly. Though I also like the `%<>%` function which is imported by `magrittr` for very specific use-cases. Not gonna argue about `dplyr`--do whatever the group wants.

For loops are certainly one way to do it, though I think vectorized operations should be preferred when possible since they're simpler to understand and it prevents writing a ton of boilerplate code. 

Ex. This should work fine. Just annoying to retype.
```{r}
names(df) <- gsub(" ", "_", names(df))
names(df) <- gsub(". ", "", names(df))
```
