### ISSUE TITLE
Modify Plotting Exercises to Use ggplot

### ISSUE THREAD

**Issue by mbergins** [How-to-Learn-to-Code/rclass#21]
Rework the plotting lessons to use ggplot instead of base R plotting.

**Comment by mbergins** [comment]
My plan is leave the current plotting lesson alone and adding plotting-ggplot.Rmd and probably plotting-ggplot-advanced.Rmd. Think that makes sense?

**Comment by daynefiler** [comment]
Yea, that's fine. I'm super glad you're contributing! Did you see the CONTRIBUTING file? Maybe we should rethinking the naming for the plotting files. One idea would be to name your files ggplot1.Rmd, and ggplot2.Rmd, mine would be graphics.Rmd and the original could be changed back to plotting.Rmd. Since we will having to be typing these into the `vignette` function I think keeping them as short as possible helps.

**Comment by mbergins** [comment]
I've just been opening each lesson as though it were a standard R markdown file and going from there. I'm less familiar with the system for making vignettes, but don't have any particular problem with adapting the filenames to make that easier.

Go ahead and take a look at the issue-21 branch and make any needed modifications.

**Comment by daynefiler** [comment]
I only looked really briefly, but it looks fine. I will test the installation when you're done and  submit the PR.

**Comment by mbergins** [comment]
I still need to modify the exercises to follow along with ggplot and the description in the contributing instructions are clear on converting the markdown to a vignette. Do you like the Chapter in "R Packages" for learning the vignette system?

http://r-pkgs.had.co.nz/vignettes.html

**Comment by daynefiler** [comment]
Yes, I do. When I'm doing actual package stuff, I do not use Markdown. I prefer using Sweave, because I like the direct access to LaTeX. I actually read that page to figure out how to implement the vignettes using markdown to convert this project over to a package.
